In [334]:
%reload_ext autoreload
%autoreload 2
from models.self_teacher import SelfTeacher
from models.active_learner import ActiveLearner
from models.teacher import Teacher

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [351]:
at = ActiveLearner(3, "boundary")
st = SelfTeacher(3, "boundary")
t = Teacher(3, "boundary")

In [348]:
t.learner_prior.shape

(4, 3, 2)

In [350]:
a = np.array([1, 1, 1, 1])


4

In [342]:
st.update_learner_posterior()
print(st.get_learner_posterior())
st.update_self_teaching_posterior()
print(st.get_self_teaching_posterior())

[[[ 0.          1.        ]
  [ 0.          0.5       ]
  [ 0.          0.33333333]]

 [[ 0.33333333  0.        ]
  [ 0.          0.5       ]
  [ 0.          0.33333333]]

 [[ 0.33333333  0.        ]
  [ 0.5         0.        ]
  [ 0.          0.33333333]]

 [[ 0.33333333  0.        ]
  [ 0.5         0.        ]
  [ 1.          0.        ]]]
[[[ 0.32467532  0.32467532]
  [ 0.35064935  0.35064935]
  [ 0.32467532  0.32467532]]

 [[ 0.32467532  0.32467532]
  [ 0.35064935  0.35064935]
  [ 0.32467532  0.32467532]]

 [[ 0.32467532  0.32467532]
  [ 0.35064935  0.35064935]
  [ 0.32467532  0.32467532]]

 [[ 0.32467532  0.32467532]
  [ 0.35064935  0.35064935]
  [ 0.32467532  0.32467532]]]
[[[ 0.          1.        ]
  [ 0.          0.5       ]
  [ 0.          0.33333333]]

 [[ 0.33333333  0.        ]
  [ 0.          0.5       ]
  [ 0.          0.33333333]]

 [[ 0.33333333  0.        ]
  [ 0.5         0.        ]
  [ 0.          0.33333333]]

 [[ 0.33333333  0.        ]
  [ 0.5         0.        

In [292]:
27/77

0.35064935064935066

In [233]:
t.update_learner_posterior()
t.get_learner_posterior()

array([[[ 0.        ,  1.        ],
        [ 0.        ,  0.5       ],
        [ 0.        ,  0.33333333]],

       [[ 0.33333333,  0.        ],
        [ 0.        ,  0.5       ],
        [ 0.        ,  0.33333333]],

       [[ 0.33333333,  0.        ],
        [ 0.5       ,  0.        ],
        [ 0.        ,  0.33333333]],

       [[ 0.33333333,  0.        ],
        [ 0.5       ,  0.        ],
        [ 1.        ,  0.        ]]])

In [286]:
posterior = t.get_learner_posterior()
entropy_posterior = -np.nansum(np.log(posterior) * posterior, axis=0)
print(entropy_posterior)
entropy_prior = -np.array([[np.log(1/4), np.log(1/4)], 
                          [np.log(1/4), np.log(1/4)], 
                          [np.log(1/4), np.log(1/4)]])
print(entropy_prior)
entropy_diff = entropy_prior - entropy_posterior
print(entropy_diff)
ys = np.array([[3/4, 1/4], [1/2, 1/2], [1/4, 3/4]])
print(np.sum(ys * entropy_diff, axis=1))
print(ys * entropy_diff)

[[ 1.09861229 -0.        ]
 [ 0.69314718  0.69314718]
 [-0.          1.09861229]]
[[ 1.38629436  1.38629436]
 [ 1.38629436  1.38629436]
 [ 1.38629436  1.38629436]]
[[ 0.28768207  1.38629436]
 [ 0.69314718  0.69314718]
 [ 1.38629436  0.28768207]]
[ 0.56233514  0.69314718  0.56233514]
[[ 0.21576155  0.34657359]
 [ 0.34657359  0.34657359]
 [ 0.34657359  0.21576155]]


//anaconda/envs/py36/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in log
  from ipykernel import kernelapp as app
//anaconda/envs/py36/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in multiply
  from ipykernel import kernelapp as app


In [256]:
# self teacher prior
(1/4 * np.log(1/4)) * 4

-1.3862943611198906

In [258]:
# self teacher likelihood
np.log(1/4) - np.log(1/2)

-0.69314718055994529

In [259]:
at

In [293]:
foo = [at.expected_information_gain(i) for i in range(3)] 

In [294]:
foo / np.sum(foo)

array([ 0.30934632,  0.38130736,  0.30934632])